set runtimepath+=~/.lotus_vim

source ~/.lotus_vim/func.vim
source ~/.lotus_vim/basic.vim
source ~/.lotus_vim/color.vim
source ~/.lotus_vim/encoding.vim
source ~/.lotus_vim/ignore.vim
source ~/.lotus_vim/mappings.vim
source ~/.lotus_vim/plugin.vim
source ~/.lotus_vim/lan.vim

try
    source ~/.lotus_vim/my_configs.vim
catch
endtry
