#!/bin/bash

if [ $# -lt 1 ]
then
echo "You need to specify one workspace name."
echo "Usage tmux_apporc <workspace_name>"
exit 1
fi

workspace=${1}

if [ "x${workspace}" != "x" -a -f ~/.tmux/${workspace}.conf ]
then
  exec /usr/bin/tmux source-file ~/.tmux/${workspace}.conf
else
  echo "Workspace ${workspace} doesn't exist."
  exit 1
fi
